import type { Metadata } from "next";
import "./scss/fonts.scss";
import "./globals.css";
import "./scss/common.scss";
import MainLayout from "./common/mainLayout";
import { ConfigProvider } from "antd";

export const metadata: Metadata = {
  title: "PROFILE | TRAN PHUONG NAM",
  description: "Generated by Tran Phuong Nam",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConfigProvider
      theme={{
        token: {
          fontFamily: "'Saira Condensed', sans-serif",
          fontSize: 25,
        },
      }}
    >
      <MainLayout children={children}/>
    </ConfigProvider>
  );
}
